"""
generate_inserts.py — export ALL player_stats + goalkeeper_stats rows as
INSERT OR IGNORE statements and append them to worldcup26_results.sql.

Run once after fbref_batch.py has loaded all matches.
INSERT OR IGNORE is idempotent in the DB (UNIQUE on player_id, match_id).
Running this script twice will duplicate lines in the .sql file — run once,
or remove the generated block before re-running.

Usage (from WSL):
    python3 generate_inserts.py
"""
import os
import logging
import sqlite3
import pandas as pd

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
DB_PATH     = os.path.join(BASE_DIR, "worldcup26.db")
RESULTS_SQL = os.path.join(BASE_DIR, "worldcup26_results.sql")
LOG_PATH    = os.path.join(BASE_DIR, "worldcup26.log")

logging.basicConfig(
    filename=LOG_PATH,
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# stat_id excluded — AUTOINCREMENT, DB assigns it on rebuild
PLAYER_COLS = [
    "player_id", "match_id",
    "minutes_played", "goals", "assists", "pk_made", "pk_att",
    "shots", "shots_on_goal", "yellow_cards", "red_cards",
    "fouls", "fouls_drawn", "offsides", "crosses", "tackles_won",
    "interceptions", "own_goals", "pk_won", "pk_conceded",
]

KEEPER_COLS = [
    "player_id", "match_id",
    "minutes_played", "shots_on_target_against", "goals_against", "saves",
]


def fmt_val(v):
    """Scalar → SQL literal: integer or NULL."""
    if pd.isna(v):
        return "NULL"
    return str(int(v))


def rows_to_inserts(df, table, cols):
    """Return a list of INSERT OR IGNORE statements, one per row."""
    col_list = ", ".join(cols)
    lines = []
    for _, row in df.iterrows():
        vals = ", ".join(fmt_val(row[c]) for c in cols)
        lines.append(f"INSERT OR IGNORE INTO {table} ({col_list}) VALUES ({vals});")
    return lines


def main():
    conn = None
    try:
        conn = sqlite3.connect(DB_PATH)
        player_df = pd.read_sql(
            "SELECT * FROM player_stats ORDER BY match_id, player_id",
            conn,
        )
        keeper_df = pd.read_sql(
            "SELECT * FROM goalkeeper_stats ORDER BY match_id, player_id",
            conn,
        )
    finally:
        if conn:
            conn.close()

    # Warn and drop orphaned rows (player_id NULL = not found in players table)
    null_p = player_df["player_id"].isna().sum()
    if null_p:
        logging.warning(f"generate_inserts: {null_p} player_stats rows with NULL player_id — skipped.")
        player_df = player_df[player_df["player_id"].notna()].copy()

    null_k = keeper_df["player_id"].isna().sum()
    if null_k:
        logging.warning(f"generate_inserts: {null_k} goalkeeper_stats rows with NULL player_id — skipped.")
        keeper_df = keeper_df[keeper_df["player_id"].notna()].copy()

    player_lines = rows_to_inserts(player_df, "player_stats", PLAYER_COLS)
    keeper_lines = rows_to_inserts(keeper_df, "goalkeeper_stats", KEEPER_COLS)

    block = (
        "\n\n-- ============================================================\n"
        "-- player_stats + goalkeeper_stats — generated by generate_inserts.py\n"
        "-- ============================================================\n\n"
        + "\n".join(player_lines)
        + "\n\n"
        + "\n".join(keeper_lines)
        + "\n"
    )

    with open(RESULTS_SQL, "a", encoding="utf-8") as f:
        f.write(block)

    logging.info(
        f"generate_inserts: {len(player_lines)} player rows, "
        f"{len(keeper_lines)} keeper rows appended to worldcup26_results.sql."
    )
    print(
        f"Done — {len(player_lines)} player inserts, "
        f"{len(keeper_lines)} keeper inserts appended to worldcup26_results.sql."
    )


if __name__ == "__main__":
    main()
